### ISSUE TITLE
Report “Client Records with Missing Phone Number” missing filter on Client field

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/PMM#188]
**Issue:**
The PMM packaged report called “Client Records with Missing Phone Number” is a report that drives a dashboard on the PMM App Home tab which is supposed to indicate the number of Contact records marked as "Client", but have a missing phone number. The report is missing the Client = True filter in the Package (was included in the NPSP Trial with PMM), which is causing all Contacts with a missing phone number to appear.

**Steps to Reproduce:**
1. Within an org that has PMM installed (not from the Trial version), navigate to the “Client Records with Missing Phone Number” report. Click Edit.
2. Click on the Filters pane, and note that there is no "Client" = True filter.

![PMM Report Missing Client Filter](https://user-images.githubusercontent.com/37851761/80427484-b1f32880-889c-11ea-9f9d-c3cbde5a0b1c.png)

**Workaround:**
Modify the report filter to include a Client = True filter, and save the Report.

**Comment by kselvocki** [comment]
Fixed by PR #191
