### ISSUE TITLE
PMM in NPSP Trial - "Viewing as" Access Error appears in dashboard component

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/PMM#196]
**Issue:**
When viewing Home Tab Dashboard or the "Sample Program Management Dashboard" an error appears on the component for the Services Delivered (Year to Date) resport (which uses the report type service Deliveries with Service). 
- Error: "We can't show this table because the "Viewing As" person doesn't have access to all the fields."
- The error presents itself regardless of the viewing user, and if there is data, and after confirming the running user does have access to fields in the report.
- The underlying report is accessible and shows the data values as expected.
- This error only appears in an org spun up from the NPSP Trial with PMM installed, and doesn't appear in the actual TSO org, nor in an org that has PMM installed via MetaDeploy package installer.

![PMM Home Page Dashboard](https://user-images.githubusercontent.com/37851761/80622409-99e6ea80-89fd-11ea-9353-2e493aafe825.png)

**Steps to Reproduce:**
1. In an org that has been created via the NPSP with PMM trial, navigate to the Program Management Module App, and view Home page. 
2. Or, navigate to the "Sample Program Management Dashboard".

Further investigation and potential workarounds for the Trial will be added to internal Work Item.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZfeQAE" target="_blank">W-041116</a>

**Comment by coriobriensfdo** [comment]
Closing this Issue as we are solutioning ways to resolve this before Trial with PMM go live May 5th.
