### ISSUE TITLE
Adding Contact to a Completed or Cancelled Program Shows a Confusing Error Message

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/PMM#201]
**Issue:**

When adding a new Contact to a Program (via a Program Engagement record), results in an error if the Program has a Completed or Cancelled Status. The error reads as "Value does not exist or does not match filter criteria", which is confusing as it doesn't specify the problem lies with the status of the Program. 
![Screen Shot 2020-05-01 at 2 29 00 PM](https://user-images.githubusercontent.com/37851761/80844157-e75c8680-8bba-11ea-8fb5-8ac000fc8b7e.png)

The Program Engagement's "Program" lookup field has a packaged lookup filter that is throwing the error. It's currently configured to have Status = Active or Planned. 

Also, as an Admin I can modify the values in the Program Status field but I'm unable to edit a packaged lookup filter, meaning the filter will no longer match my business criteria. 

**Steps to Repeat:**

1. Create a Program with the status of Completed or Cancelled.
2. Click add the "Add a Contact to Program" button. 
3. Enter Contact, Role, Stage details, and click Save.
Expected: Due to the Status of the Program, error message indicates Contact cannot be added to Program as the Program is Completed or Cancelled. 
Actual: Error message "Value does not exist or does not match filter criteria" is displayed.

**Workaround:**
Until a fix an be put in place, make sure you are adding a Contact to a Planned or Active Program.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZniQAE" target="_blank">W-041172</a>
