### ISSUE TITLE
display issues

### ISSUE THREAD

**Issue by mattmartin26** [SalesforceFoundation/PMM#214]
Having display issues in the left block every time I am on the Program page layout - all the fields on the left hand side get cut off mid-word, sometimes twice. 

![image](https://user-images.githubusercontent.com/60525986/82839863-9ec87e00-9e85-11ea-9b01-8c1e066eb6b8.png)

**Comment by coriobriensfdo** [comment]
Hi @mattmartin26 we don't support PMM here in the GitHub repo. Can you post in the [PMM group](https://powerofus.force.com/s/group/0F91E000000bs8XSAQ/program-management-module-pmm) in the Power of Us Hub instead? When you post there, please also indicate the current version of PMM in your org.
