### ISSUE TITLE
No option to add Program Cohort to Service Session

### ISSUE THREAD

**Issue by chericodes** [SalesforceFoundation/PMM#336]
In the  _Schedule Services_ section of the PMM _Work with Services_ documentation, item 10 advices "Review the Service Sessions and click Next." When I do this, the circle-of-thinking-dots just keeps spinning and never resolves to the dialog where, presumably, I could complete item 11 and add a Program Cohort. I can click Next to move on from the non-responsive dialog, but I see nowhere to add a Program Cohort once the Service is set up. Adding Service Participants one at a time will be painful, so the Cohort option is important to my client. 

Thanks to all working on this great addition to the nonprofit lineup!

**Comment by coriobriensfdo** [comment]
Hi @chericodes we don't provide support here in GitHub. Can you instead post to the [PMM group in the Power of Us Hub](https://powerofus.force.com/s/group/0F91E000000bs8XSAQ/program-management-module-pmm)? I can assist there and if there's a bug in the product open/reopen an Issue here on GitHub.
