### ISSUE TITLE
Field labels do not align with fields in the Attendance component and on the printable view page / tab if Compact display density setting is used

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/PMM#410]
### Summary of the Issues

The Service Session page contains a Lighting Component called Attendance. This component allows a user to track attendance on a Service Session to create Service Deliveries for everyone who attended or was absent from that session.

If a user selects the Compact display density setting in Lightning, the Attendance Status field label will display in-line with the picklist field and will wrap onto two lines mid-word (see screenshot 1). This is replicated on the Attendance printable view page/tab. Additionally, the majority of the service session fields across the top of the Attendance printable view page / tab will wrap mid-word (see screenshot 2)

**Screenshot 1**
<img width="1065" alt="Component" src="https://user-images.githubusercontent.com/59653509/106970212-4fd92500-6744-11eb-95ed-0bc71c39d5b2.png">

**Screenshot 2**
<img width="1620" alt="Printable view tab" src="https://user-images.githubusercontent.com/59653509/106970233-5798c980-6744-11eb-89b3-e8f707bd9670.png">

### Steps to Reproduce

- Create scratch org
- Run the install_prod flow
- Login as user and switch to the Compact density setting
- Navigate to Service Schedules, load the Ocean Exploration Series record from the sample dataset
- Navigate to one of the Service Session records
- Confirm the Attendance Status label wraps on to two lines mid-word in the Track Attendance component
- Click Printable View
- Confirm the Attendance Status label wraps on to two lines mid-word and that the Service Session fields across the top of the component also wrap mid-word

### Workaround

- Switch back to the Comfy display density setting

**Comment by kschaefges** [comment]
Fixed with PMM release 1.21
