### ISSUE TITLE
Field labels do not align with fields and others wrap mid-word in the Service Schedule component if the Compact display density setting is used

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/PMM#411]
### Summary of the Issues

The Service Schedule component wizard allows a user to create one-time or recurring events for groups or individuals, such as classes, mentoring sessions, support groups, or community events.

If a user selects the Compact display density setting in Lightning, screen one of the wizard displays some fields that are misaligned (the Participant Capacity and Default Service Quantity fields) and that both the Service Schedule End Date and the Number of Service Sessions field labels wrap mid-word over many lines (see screenshot below).

Screenshot
<img width="1457" alt="Compact" src="https://user-images.githubusercontent.com/59653509/106971659-42716a00-6747-11eb-9720-372909a4f782.png">

### Steps to Reproduce

- Create scratch org
- Run the install_prod flow
- Login as user and switch to the Compact density setting
- Navigate to Service Schedules, click New
- Confirm the Participant Capacity and Default Service Quantity fields are misaligned
- Confirm the Service Schedule End Date and the Number of Service Sessions fields wrap mid-word, and over many lines

### Workaround

- Switch back to the Comfy display density setting

**Comment by kschaefges** [comment]
Fixed with PMM release 1.21
