### ISSUE TITLE
Double-clicking on Save when creating a Service Schedule results in duplicate Service Schedule records

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/PMM#412]
### Summary of the Issue

The Service Schedule component wizard allows a user to create one-time or recurring events for groups or individuals, such as classes, mentoring sessions, support groups, or community events.

The last screen of the Service Schedule wizard component contains a Save button. If a user double-clicks rather than single-clicks on this button they will create duplicate Service Service records. This will also result in duplicate associate records (e.g Service Sessions and Service Participants) for the duplicate record.

### Steps to Reproduce

- Navigate to Service Schedules, click New
- Click through the screens to the final screen and double-click Save
- Confirm that a duplicate Service Schedule record has been created

### Workaround

- A user should single-click on Save rather than double-click

**Comment by kschaefges** [comment]
Fixed with PMM release 1.21
